version: 0.0
os: linux
files:
  - source: /
    destination: /flaskapp/
hooks:
  BeforeInstall:
    - echo "before install"
  AfterInstall:
    - location: /flaskapp/script.sh
      timeout: 300
      runas: root


